create extension if not exists pgcrypto;

create table if not exists public.questions (
  id bigint generated by default as identity primary key,
  question_code text not null unique,
  question_type text not null check (question_type in ('D', 'I', 'S', 'C')),
  question_text text not null,
  sort_order integer not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists questions_type_order_idx
  on public.questions (question_type, sort_order);

alter table public.questions enable row level security;

grant select, insert, update, delete on public.questions to service_role;

create table if not exists public.assessment_sessions (
  assessment_id text primary key,
  created_at timestamptz not null,
  updated_at timestamptz not null,
  status text not null,
  current_page integer not null default 0,
  identity jsonb not null default '{}'::jsonb,
  questions_presented jsonb not null default '[]'::jsonb,
  answers jsonb not null default '{}'::jsonb,
  scores jsonb,
  report jsonb,
  feedback jsonb,
  page_size integer not null default 4,
  total_questions integer not null default 20,
  page_count integer not null default 5,
  completed_at timestamptz
);

create index if not exists assessment_sessions_status_idx
  on public.assessment_sessions (status);

create index if not exists assessment_sessions_updated_at_idx
  on public.assessment_sessions (updated_at desc);

alter table public.assessment_sessions enable row level security;

grant select, insert, update, delete on public.assessment_sessions to service_role;

create table if not exists public.assessment_events (
  id bigint generated by default as identity primary key,
  assessment_id text not null references public.assessment_sessions (assessment_id) on delete cascade,
  event_type text not null,
  transition jsonb,
  payload jsonb not null default '{}'::jsonb,
  snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists assessment_events_assessment_id_idx
  on public.assessment_events (assessment_id, created_at desc);

create index if not exists assessment_events_type_idx
  on public.assessment_events (event_type);

alter table public.assessment_events enable row level security;

grant select, insert, update, delete on public.assessment_events to service_role;

-- Question seed is inserted by the application on first assessment start.
-- This keeps the 30-question bank dynamic while avoiding duplicate manual setup.
