-- Adds 70 new assessment questions to expand the live bank.
insert into public.questions (
  question_code,
  question_type,
  question_text,
  sort_order,
  is_active
) values
  ('D13', 'D', 'I like setting a fast pace when a team needs momentum.', 13, true),
  ('D14', 'D', 'I am willing to make a tough call when the options are clear enough.', 14, true),
  ('D15', 'D', 'I push for solutions instead of spending too long on the problem.', 15, true),
  ('D16', 'D', 'I like taking charge when a project starts to drift.', 16, true),
  ('D17', 'D', 'I feel comfortable challenging decisions that slow progress.', 17, true),
  ('D18', 'D', 'I prefer clear accountability over vague shared ownership.', 18, true),
  ('D19', 'D', 'I am energized by goals that are ambitious and time-bound.', 19, true),
  ('D20', 'D', 'I usually say what needs to be said, even if it feels blunt.', 20, true),
  ('D21', 'D', 'I like testing ideas through action instead of endless discussion.', 21, true),
  ('D22', 'D', 'I prefer to fix problems directly rather than wait for perfect conditions.', 22, true),
  ('D23', 'D', 'I am comfortable being held responsible for results.', 23, true),
  ('D24', 'D', 'I like work that lets me influence direction, not just follow it.', 24, true),
  ('D25', 'D', 'I often notice where a plan is wasting time or effort.', 25, true),
  ('D26', 'D', 'I am not afraid to set boundaries when expectations are unrealistic.', 26, true),
  ('D27', 'D', 'I prefer a confident yes or no over a long delay.', 27, true),
  ('D28', 'D', 'I am quick to move a meeting toward a decision.', 28, true),
  ('D29', 'D', 'I enjoy roles where progress is visible and measurable.', 29, true),
  ('D30', 'D', 'I like being the person who keeps everyone focused on the target.', 30, true),
  ('I13', 'I', 'I enjoy making new teammates feel welcome quickly.', 13, true),
  ('I14', 'I', 'I naturally add energy when a group starts to feel flat.', 14, true),
  ('I15', 'I', 'I like roles where I can share ideas and get people excited.', 15, true),
  ('I16', 'I', 'I find it easy to turn a quiet conversation into a lively one.', 16, true),
  ('I17', 'I', 'I enjoy celebrating small wins with the people around me.', 17, true),
  ('I18', 'I', 'I like being in settings where communication comes naturally.', 18, true),
  ('I19', 'I', 'I tend to bring optimism when a team is under pressure.', 19, true),
  ('I20', 'I', 'I enjoy explaining ideas in a way that gets people interested.', 20, true),
  ('I21', 'I', 'I feel comfortable connecting people who should meet each other.', 21, true),
  ('I22', 'I', 'I like work that involves presentations, calls, or group discussions.', 22, true),
  ('I23', 'I', 'I often notice what can make a team feel more engaged.', 23, true),
  ('I24', 'I', 'I like helping others feel heard and included.', 24, true),
  ('I25', 'I', 'I enjoy being the person who keeps morale up.', 25, true),
  ('I26', 'I', 'I find it easy to adapt my style to different personalities.', 26, true),
  ('I27', 'I', 'I like opening up conversations with people I do not know well.', 27, true),
  ('I28', 'I', 'I usually bring a positive tone to the room.', 28, true),
  ('I29', 'I', 'I enjoy persuading others through enthusiasm and stories.', 29, true),
  ('I30', 'I', 'I like turning ideas into something people want to join.', 30, true),
  ('S13', 'S', 'I prefer a calm pace that lets people do quality work.', 13, true),
  ('S14', 'S', 'I am good at keeping the team steady when plans change.', 14, true),
  ('S15', 'S', 'I like routines that help work feel predictable.', 15, true),
  ('S16', 'S', 'I often notice when someone needs quiet support.', 16, true),
  ('S17', 'S', 'I prefer to resolve tension gently rather than forcefully.', 17, true),
  ('S18', 'S', 'I am comfortable being the reliable person others can count on.', 18, true),
  ('S19', 'S', 'I like giving people time to think before expecting a response.', 19, true),
  ('S20', 'S', 'I usually stay patient when a task takes longer than expected.', 20, true),
  ('S21', 'S', 'I value long-term trust more than short-term excitement.', 21, true),
  ('S22', 'S', 'I like helping teams stay coordinated without creating pressure.', 22, true),
  ('S23', 'S', 'I am comfortable working through repetitive tasks if they matter.', 23, true),
  ('S24', 'S', 'I prefer to build trust slowly rather than rush relationships.', 24, true),
  ('S25', 'S', 'I like environments where people treat one another respectfully.', 25, true),
  ('S26', 'S', 'I often help others feel settled when things get hectic.', 26, true),
  ('S27', 'S', 'I prefer clear, steady expectations over constant surprise.', 27, true),
  ('S28', 'S', 'I like roles where consistency is more valued than urgency.', 28, true),
  ('S29', 'S', 'I tend to keep things moving smoothly without drawing attention.', 29, true),
  ('C13', 'C', 'I like having enough data before I make a decision.', 13, true),
  ('C14', 'C', 'I naturally check for errors before I share my work.', 14, true),
  ('C15', 'C', 'I prefer tasks with clear standards and measurable quality.', 15, true),
  ('C16', 'C', 'I like understanding the logic behind a process before using it.', 16, true),
  ('C17', 'C', 'I usually notice when details do not line up.', 17, true),
  ('C18', 'C', 'I prefer organized information over scattered notes.', 18, true),
  ('C19', 'C', 'I feel more confident when work has a clear method.', 19, true),
  ('C20', 'C', 'I like improving a system so it works more accurately.', 20, true),
  ('C21', 'C', 'I often ask questions until the details are clear.', 21, true),
  ('C22', 'C', 'I prefer well-documented instructions to guesswork.', 22, true),
  ('C23', 'C', 'I like comparing options carefully before choosing one.', 23, true),
  ('C24', 'C', 'I tend to review work for accuracy, consistency, and completeness.', 24, true),
  ('C25', 'C', 'I enjoy roles where precision makes a real difference.', 25, true),
  ('C26', 'C', 'I like breaking a complex problem into smaller parts.', 26, true),
  ('C27', 'C', 'I usually prepare carefully so fewer mistakes happen later.', 27, true),
  ('C28', 'C', 'I prefer facts, examples, and evidence over assumptions.', 28, true),
  ('C29', 'C', 'I feel satisfied when a result is neat, correct, and reliable.', 29, true)
on conflict (question_code) do update set
  question_type = excluded.question_type,
  question_text = excluded.question_text,
  sort_order = excluded.sort_order,
  is_active = excluded.is_active;
